### ISSUE TITLE
Найти задачи

### ISSUE THREAD

**Issue by da-the-dev** [da-the-dev/interior_points#1]
Нужно найти и накидать задач с решениями для алгоса

**Comment by NikaChek** [comment]
[Interior_Point_problem1.pdf](https://github.com/da-the-dev/interior_points/files/13193258/Interior_Point_problem1.pdf)

**Comment by kkkaterinaaa** [comment]
[interioir_point_problem2.pdf](https://github.com/da-the-dev/interior_points/files/13198158/interioir_point_problem2.pdf)
